"use strict";(self.webpackChunkreact_form_simple=self.webpackChunkreact_form_simple||[]).push([[752],{77752:function(y,f,c){c.r(f),c.d(f,{SandpackStatic:function(){return g}});var p=c(51869),v=c(33679),d=c(27757),h=c(32308),b=c(95002),P=c(38471),w=function(a,r,t){var e=a.exec(r);if(e&&e.length>=1){var i=e.index+e[0].length,o=r.substring(0,i),n=r.substring(i);return o+t+n}},m=function(a){return typeof a=="string"?a:new TextDecoder().decode(a)},E=function(a){var r=m(a),t=new DOMParser,e=t.parseFromString(r,"text/html");e.documentElement.getAttribute("lang")||e.documentElement.setAttribute("lang","en");var i=e.documentElement.outerHTML;return`<!DOCTYPE html>
`.concat(i)},g=function(a){(0,p.g)(r,a);function r(t,e,i){i===void 0&&(i={});var o,n=a.call(this,t,e,i)||this;if(n.files=new Map,n.status="initializing",n.emitter=new d.E,n.previewController=new v.PreviewController({baseUrl:(o=i.bundlerURL)!==null&&o!==void 0?o:"https://preview.sandpack-static-server.codesandbox.io",getFileContent:function(u){var s=n.files.get(u);if(!s)throw new Error("File not found");if(u.endsWith(".html")||u.endsWith(".htm"))try{s=E(s),s=n.injectProtocolScript(s),s=n.injectExternalResources(s,i.externalResources),s=n.injectScriptIntoHead(s,{script:d.c,scope:{channelId:(0,d.g)()}})}catch(_){console.error("Runtime injection failed",_)}return s}}),typeof t=="string"){n.selector=t;var l=document.querySelector(t);n.element=l,n.iframe=document.createElement("iframe")}else n.element=t,n.iframe=t;return n.iframe.getAttribute("sandbox")||(n.iframe.setAttribute("sandbox","allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"),n.iframe.setAttribute("allow","accelerometer; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; clipboard-write;")),n.eventListener=n.eventListener.bind(n),typeof window!="undefined"&&window.addEventListener("message",n.eventListener),n.updateSandbox(),n}return r.prototype.injectContentIntoHead=function(t,e){var i;return t=m(t),t=(i=w(/<head[^<>]*>/g,t,`
`+e))!==null&&i!==void 0?i:e+`
`+t,t},r.prototype.injectProtocolScript=function(t){var e=`<script>
  window.addEventListener("message", (message) => {
    if(message.data.type === "refresh") {
      window.location.reload();
    }
  })
<\/script>`;return this.injectContentIntoHead(t,e)},r.prototype.injectExternalResources=function(t,e){e===void 0&&(e=[]);var i=e.map(function(o){var n=o.match(/\.([^.]*)$/),l=n==null?void 0:n[1];if(l==="css"||o.includes("fonts.googleapis"))return'<link rel="stylesheet" href="'.concat(o,'">');if(l==="js")return'<script src="'.concat(o,'"><\/script>');throw new Error("Unable to determine file type for external resource: ".concat(o))}).join(`
`);return this.injectContentIntoHead(t,i)},r.prototype.injectScriptIntoHead=function(t,e){var i=e.script,o=e.scope,n=o===void 0?{}:o,l=`
    <script>
      const scope = `.concat(JSON.stringify(n),`;
      `).concat(i,`
    <\/script>
    `).trim();return this.injectContentIntoHead(t,l)},r.prototype.updateSandbox=function(t,e){t===void 0&&(t=this.sandboxSetup);var i=(0,d.f)(t.files);this.dispatch({codesandbox:!0,modules:i,template:t.template,type:"compile"})},r.prototype.compile=function(t){return(0,p._)(this,void 0,void 0,function(){var e;return(0,p.a)(this,function(i){switch(i.label){case 0:return this.files=new Map(Object.entries(t)),[4,this.previewController.initPreview()];case 1:return e=i.sent(),this.iframe.setAttribute("src",e),this.status="done",this.dispatch({type:"done",compilatonError:!1}),this.dispatch({type:"urlchange",url:e,back:!1,forward:!1}),[2]}})})},r.prototype.eventListener=function(t){if(t.source===this.iframe.contentWindow){var e=t.data;e.codesandbox&&this.dispatch(e)}},r.prototype.dispatch=function(t){var e;switch(t.type){case"compile":this.compile(t.modules);break;default:(e=this.iframe.contentWindow)===null||e===void 0||e.postMessage(t,"*"),this.emitter.dispatch(t)}},r.prototype.listen=function(t){return this.emitter.listener(t)},r.prototype.destroy=function(){this.emitter.cleanup(),typeof window!="undefined"&&window.removeEventListener("message",this.eventListener)},r}(h.S)}}]);
